name: splunk-appinspect
on:
  push:
    branches:
      - devel
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install dependencies
        run: sudo apt-get install -y jq
      - name: Download packaging toolkit
        run: wget https://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.1.tar.gz
      - name: Install packaging toolkit
        run: pip install splunk-packaging-toolkit-1.0.1.tar.gz
      - name: Package app
        run: |
          slim package -o ~/build/packages SA-CrowdstrikeDevices
          cd ~/build/packages
      - name: Download and run helper script
        run: wget https://raw.githubusercontent.com/ZachChristensen28/splunk-app-dev/master/validate.sh && chmod +x validate.sh
      - name: Validate credentials
        run: |
          export API_USER=${{ secrets.API_USER }}
          export API_PASS=${{ secrets.API_PASS }}
          ./validate.sh -v
      - name: Submit App for vetting
        run: ./validate.sh submit $(ls)
      - name: Check Status
        run: ./validate.sh status
